name: CI with Pytest and CodeQL

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          PYTHONPATH=. pytest tests --maxfail=1 --disable-warnings -q

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [python]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL analysis for the specified language.
      # For Python, this step automatically creates a database from the source code.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # The autobuild step is removed.
      # For Python, it's not needed and can sometimes cause issues.
      # CodeQL will perform its analysis directly on the source code provided by `checkout`.

      # Runs the CodeQL analysis queries on the generated database.
      # This step will identify potential security vulnerabilities and bugs.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3