name: SonarQube analysis

on:
  push:
    branches: [ "feature/x" ]
  
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml  # generates coverage.xml needed by SonarQube 

      - name: Debug - List directory contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents recursively:"
          find . -type d -name "app" 2>/dev/null || echo "No 'app' directory found"
          echo "All directories:"
          find . -type d | head -20

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://host.docker.internal:9003"
        with:
          args: >
            -Dsonar.projectKey=branchprotection-git
            -Dsonar.sources=app
            -Dsonar.language=py
            -Dsonar.python.coverage.reportPaths=coverage.xml