name: SonarQube analysis

on:
  push:
    branches: [ "feature/x" ]
  
  workflow_dispatch:

jobs:
  sonarqube-analysis:
    runs-on: self-hosted
    name: SonarQube Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml  # generates coverage.xml needed by SonarQube
        continue-on-error: true  # This is the key addition!

      - name: Debug - List directory contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents recursively:"
          find . -type d -name "app" 2>/dev/null || echo "No 'app' directory found"
          echo "All directories:"
          find . -type d | head -20

      - name: Download and setup SonarScanner
        run: |
          if [ ! -d "sonar-scanner-5.0.1.3006-linux" ]; then
            wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip
          fi
          export PATH=$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://host.docker.internal:9003"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=branchprotection-git \
            -Dsonar.sources=app \
            -Dsonar.language=py \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN