name: Hello World with Approval

on:
  workflow_run:
    workflows: ["SonarQube analysis"]  # Name of the first workflow
    types:
      - completed  # Runs when the trigger workflow completes

jobs:
  hello:
    # Only run if the trigger workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: approval-gate  # Links to the environment with approval gate

    steps:
      - name: Echo Hello World
        run: echo "hello world"